name: Test deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable
      - name: Test build website
        run: yarn build
